### ISSUE TITLE
Vai trò (Role) của Tester là gì ?

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#19]
Hmm. Một câu hỏi vớ vẩn. Nó quá hiển nhiên rồi. Chúng tôi đang kiểm soát chất lượng, đảm bảo chất lượng của dự án....

Họ mong muốn bạn phải bằng cách nào đó "phá hủy" bằng được thành quả của đội Dev trước khi nó được release và nếu sau khi release mà sản phẩm có lỗi thì điều đó có nghĩa là đội Tester đã chưa đập một búa đủ mạnh vào sản phẩm của Dev ?

Nếu ai đó nghĩ rằng: Chúng tôi đang có vấn đề về lỗi sản phẩm, Chúng tôi cần những người để giúp chúng tôi đảm bảo chất lượng (Tester) và khi chất lượng không được như kỳ vọng người bị đổi lỗi là Tester thì phần nhiều chúng ta đang hiểu không đúng về vai trò của Tester.

Tại sao trong team lại có nhiều roles: Dev, Tester, BA.... là bởi nó quy định mối quan hệ giữa các role trong team. Bạn có thể từ vai trò của mình "thương lượng" với các bên liên quan.

Hãy tượng tưởng dự án của bạn là một trận Đế Chế ( OAE). Một loại game chiến thuật.

Có 2 chế độ chơi: Một là toàn bộ bản độ đã được chiếu sáng khá dễ dàng để bạn có thể cử nông dân đến các mỏ quả để thu hoạch vì bạn nhìn thấy luôn. Nó giống như một chuyến xe đi và ban ngày. Bạn nhìn thấy rõ đường đi nước bước của mình rồi. Nó giống như những dự án đơn giản nhưng trên thực tế các cuộc chiến tranh giải các game thủ không chơi ở chế độ này cũng giống như các dự án thực tế, Mọi cái không phải ngay từ đầu đã rõ ràng. 

Chế độ chơi thứ 2 là toàn bộ map sẽ chìm trong bóng tối giống như những chuyến xe trong đêm.

Ở đời 1: Có 3 người nông dân. Một trong công việc đầu tiên là cắt cử 1 nông dân đi dò đường (tìm nguồn lương thực). Mỗi bước di chuyển của người nông dân dò đường này sẽ tỏa vùng sáng xóa đi vùng bị mù, giúp người chơi mở rộng được vùng quan sát. Người nông dân này sẽ đóng vai trò như cái đèn pha oto khi đi trong đêm. 

Bước sang đời 2: Khi bạn chuẩn bị có lính đi đánh nhau. Bạn sẽ có một con "ngựa dò". Nó di chuyển nhanh hơn nông dân và phạm vi chiếu sáng của nó cũng rộng hơn nhưng nó không có sức chiến đấu mạnh

Nhiệm vụ của nó là scout ( thám thính, do thám), **tìm kiếm và thu thập thông tin** báo về vị trí của kẻ thù. Thông tin này đặc biệt quan trọng để cho quân đội có thể hành quân đến đúng chỗ cần đến. Nếu chỉ cần sai, Khi cắt cử quân đi mà lệch hướng tác hại là vô cùng lớn. Khi đó toàn bộ đế chế của bạn ko còn ai bảo vệ. Chỉ cần quân lính thâm nhập vào cơ sở của bạn là mọi thứ toang.

Tester cũng như nhưng người do đường kia. Công việc của họ là hoàn thành việc **tìm kiếm thông tin để giúp cho đợi phát triển đưa ra các quyết định quan trọng**.

Vậy thông tin đó là gì ? Và làm sao để tìm ra chúng ?

**Comment by nghinv** [comment]
Ý kiến của tớ thì khác. Dev & Tester hay bất cứ bên nào tham gia xây dựng nên sản phẩm đều tạo ra công trình đó là 1 sản phẩm có mục đích, có ý nghĩa, có giá trị.
Vai trò của của Tester là bảo vệ giá trị của công trình/tác phẩm đó. Khi họ nhận ra giá trị của công trình/tác phẩm thì họ bảo vệ nó.
Bằng cách:
1/ Nhận ra, quý trọng những gì mà PO/BA định nghĩa ra từ nhu cầu của người dùng, để phục vụ người dùng. Nhận ra, quý trọng ý nghĩa của sản phẩm / tác phẩm/ công trình đó giành cho người dùng.
2/ Quý trọng những gì mà những anh kỹ thuật (architecture, dev) định nghĩa ra để làm ra được 1 sản phẩm/tác phẩm/công trình mà người dùng thấy có giá trị
3/ Vun vén bảo vệ những giá trị đó bằng nhiều cách:
a. Góp ý kiến để có sản phẩm tốt hơn
b. Nhìn thấy các rủi ro, góp ý để giảm bớt rủi ro
c. Nhìn thấy lỗi của quá trình thực hiện và tìm cách loại bỏ nó
----

Nếu tester mà chỉ có đi khăng khăng làm việc trên requirement thì thực sự là khô cứng. Thiếu đi cái nhìn bao dung, khách quan, quý trọng những gì phía sau dự án... đó chính là mong muốn, tâm huyết, công sức của những người tạo ra công trình/tác phẩm đó.

Nếu chỉ khăng khăng khẳng định đúng sai thì dễ đối đầu. Nhưng nếu vun vén cho giá trị cuối cùng thì mọi thứ sẽ xoay theo chiều thuận nhất

**Comment by Jacobvu84** [comment]
@nghinv 
Những thứ bạn thảo luận, mình hoàn toàn đồng ý: Có thể nó đã được đề cập ở đây: https://github.com/Jacobvu84/diary-testing/issues/22
