### ISSUE TITLE
Nhìn Class dưới góc độ là cách mô phỏng thế giới thực ( model object)

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#2]
Đứa nhỏ sống ở thành phố hỏi tôi: "Anh ơi! Con Lợn nó như thế nào ?". Uhm, đúng rồi thành phố mà đất ở còn không có lấy đâu đất mà xây chuồng lợn để nuôi lợn. 

Lúc này tôi cố lục lại kiến thức về cách làm một bài văn `mô tả` con vật, cảnh vật: Nó có 4 chân, bàn chân nó giống đôi guốc mà chị em hay đi kìa, chân nó dài tới nách. Bụng nó to, tròn như bụng chú tư hay uống bia đầu ngõ kia. Mắt no to tròn, lông mi cong vút, dài như khi chị của em chuốt mascara. Nó kêu ụt ụt.... Nhìn cái mặt nhu nhu của nó là biết nó không hình dung ra cái thứ gì rồi. 

Tôi bảo nó lấy giấy origami ra đây, anh gấp cho.  `Gấp mô hình` xong tôi cũng ko thấy nó giống con lợn lắm. Tôi liên lấy đất nặn của nó để `nặn mô hình` con lợn. 

Tôi đã cố mọi thứ để cho một "tờ giấy trắng" có thể hiểu được cái nó muốn. Chứ không vì một động cơ đê hèn nào như vì tiền, vì muốn thể hiện sỹ diện trước mặt nó mà để nó hiểu con lợn thành con trâu hoặc một thứ gì khác.

Nó có vẻ vẫn chưa rõ lắm con lợn có phần vì năng khiếu của tôi nó không được tốt lắm. Tốn bao thời gian mà nó không hiểu nên bực nói nó. "Em y như lợn vậy". Nó lấy gương ra soi, nghiêng nghiêng cái mặt, mắt chớp chớp và nói với tôi. "Sao lại có thêm một thứ xinh đẹp như vậy trên đời này sao". 

Lúc này nhà có mạng wifi trở lại, tôi mở điện thoại định cho nó xem hình con lợn thật nhưng thôi sợ nó tổn thương =]]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/983936/110734051-9cd77c00-8259-11eb-90bb-ba63655deb44.png">

Ok, Chuyện vui thôi. Nhưng mà việc dùng ngôn ngữ mô tả, dùng giấy gấp hình, hay dùng đất nặn hình là cách mà chúng ta đang cố gắng giả lập hoặc mô phỏng lại một cái gì đó có thật ngoài đời để cho ai đó có thể hiểu được. Việc này người ta gọi là **model object**.

Hãy giả sử đứa em của tôi là cái máy tính. Vậy làm sao để nó có thể hiểu được thế giới thật của con người thông qua việc mô tả, mô phỏng, xây dựng hay giả lập các đối tượng. Không còn cách nào khác phải dùng `ngôn ngữ` của nó. Người ta gọi là ngôn ngữ lập trình. 

Thay vì dùng ngôn ngữ con người để tả đối tượng cho con người hiểu thì Dev sẽ dùng ngôn ngữ lập trình để tả đối tượng cho máy tính hiểu. Lúc đó ở ngoài đời có cái gì thì trong máy tính nó cũng có cái đó: Con người, động vật, Nhân Viên, Sinh Viên, Ngân Hàng, Hoá đơn, Tài khoản.....

Vậy bây giờ. Chúng ta sẽ chuyển đổi đối tượng ngoài đời thực và máy tính như thế nào?

**Comment by Jacobvu84** [comment]
Tạo một model cho object là thẻ căn cước công dân

![image](https://user-images.githubusercontent.com/983936/110736470-4e78ac00-825e-11eb-94b7-412a1c7c82f6.png)

Để rõ hơn bạn có thể tự quan sát thẻ căn cước của mình nếu có và QUAN SÁT xem đối tượng mình đang nhắm tới để tạo một model cho nó là gì ?

Trong ví dụ này chúng ta có thể lấy giấy bút gạch mấy cái gạch đầu dòng về THÔNG TIN như sau

```
Thẻ Căn Cước Công Dân
- Số thẻ căn cước
- Họ và tên khai sinh:
- Ngày, tháng, năm sinh:
- Giới tính
- Dân Tộc
- Quê Quán
- Nơi Thường trú:
- Có giá trị đến:
```

Việc tạo ra một class với các trường/thuộc tính (fields) ứng với thông tin phía trên. Chúng ta có thể dùng các kiểu dữ liệu nguyên thuỷ / hoặc các wrapper tương ứng của nó để biểu diễn cho các thông tin này

**Comment by Jacobvu84** [comment]
Mục đích của việc tạo ra máy tính là giúp con người có thể xử lý được dữ liệu cách nhanh chóng và chính xác. Vậy có thể ngoài đời sẽ có những đối tượng có rất nhiều thông tin, chúng ta không cần phải đưa hết nó vào trong model. Chúng ta chỉ cần đưa những thông tin nào mà chúng ta cần để phục vụ cho bài toán hay vấn đề của mình cần.

Như trong bài https://github.com/Jacobvu84/diary-testing/issues/1 đã đề cập một class gồm 2 phần: Dữ Liệu thể hiện thông qua các fields và phần xử lý dữ liệu thông qua các method.

Ở đây tôi chưa có method nào. Lý do là vì tôi không biết cục cảnh sát DKQL cư trú và DLOG về dân cư sử dụng những thông tin trên kia cho vấn đề gì nên thôi, tôi cứ bịa đại ra một vài cái....

- Thông kê xem cả nước có bao người đến tuổi về hưu từ đó xác định phần trăm số người trong độ tuổi lao động để phát triển thêm việc làm hoặc đại loại gì đó liên quan tới việc phát triển xã hội: 

Từ việc này tôi cần có một method xử lý cho tôi việc tính tuổi của công dân.

```
class TheCanCuocCongDan {

   private String maSo;
   private String hoVaTen;
   private String ngaySinh;
   private String gioiTinh ;
   private String danToc ;
   private String queQuan ;
   private String noiThuongTru ;
   private String thoiGianCoHieuLuc ;

   
   public int layTuoi(){
       return ngayHienTai - ngaySinh;
  }
 
}

```

Và cứ như vậy, tuỳ vào yêu cầu trong công việc thực tế ta sẽ có những method để xử lý dữ liệu nhằm lấy được thông tin ta cần.

Còn gì nữa không ?

**Comment by Jacobvu84** [comment]
Hãy nhìn vào 

```
   public int layTuoi(){
       return ngayHienTai - ngaySinh;
  }
```

Tôi chưa biết KIỂU DỮ LIỆU nào để biểu thị cho ngày sinh mà tôi có thể có phép toán hay method nào đó lấy để tính ra được tuổi.

Trong ví dụ của mình tôi đã biểu diễn ngày sinh theo kiểu dữ liệu String. Nhưng String không có phép toán trừ và cũng chẳng có method nào có thể giúp tôi cộng, trừ ngày tháng cả.

Vậy điều tôi cần làm là tìm kiếm xem có KIỂU DỮ LIỆU nào giúp tôi làm điều này không, Giả sử tôi có class là `Datetime`. Nó có thể giúp tôi việc cộng, trừ ngày tháng. 

Tôi sẽ viết lại code như sau

```
class TheCanCuocCongDan {

   private String maSo;
   private String hoVaTen;
   private Datetime ngaySinh;
   private String queQuan ;
   .......

   public int layTuoi(){
       Datetime dateTime = new Datetime();
       return DateTime.getYear(dateTime.now().getYear(), ngaySinh.getYear());
  }
}
```

Bạn chưa cần quan tâm vội tới việc `how` to wirte cái việc xử lý dữ liệu ngày tháng như nào. Tôi ko có ý định dạy các bạn về điều đó.

**Comment by Jacobvu84** [comment]
Tương tự như vậy, tôi muốn lấy thông tin xem không phải ở cả nước có bao người trên độ tuổi lao động mà tôi chỉ muốn kiểm tra ở một tỉnh thành nào đó thôi. 

Việc tôi biểu diễn thông tin queQuan thông qua String class cũng ko dễ dàng gì giúp tôi xác định được tỉnh thành nơi họ đăng ký thẻ căn cước. Vậy tôi cũng cần một KIỂU DỮ LIỆU (class) nào đó giúp tôi lấy được tên tỉnh thành trong queQuan. 

Tôi giả sử có một class tên là Address, nhìn nó kiểu như sau

```
class DiaChi { 

   private String soNha;
   private String duong;
   private String quanHuyen;
   private String thanhPho;
   private String quocGia;
   ........
   public String layTenThanhPho{
       return thanhPho;
   }
   
} 
```

Và tôi sẽ viết lại class 

```
class TheCanCuocCongDan {

   private String maSo;
   private String hoVaTen;
   private Datetime ngaySinh;
   private DiaChi queQuan ;
   .......

   public int layTuoi(){
       Datetime dateTime = new Datetime();
       return DateTime.getYear(dateTime.now().getYear(), ngaySinh.getYear());
  }

   public int layThanhPho(){
       Datetime dateTime = new Datetime();
       return queQuan. layTenThanhPho();
  }
}
```

Bạn thấy đó, Tôi đã vừa tạo thêm model cho 2 objects nữa là `DateTime` và `DiaChi` và giờ đối tượng `TheCanCuocCongDan` được kết hợp ( composition), được tạo ra không chỉ bởi các kiểu dữ liệu nguyên thuỷ hay từ các class wrapper tương ứng của chúng mà còn từ những kiểu dữ liệu do mình tự viết như `DataTime` hay `DiaChi`

Điều này có nghĩa là gì ?

Việc xây dựng một mô hình đối tượng ( model object) trong thực tế đời sống ko có đối tượng nào là đối tượng đơn lẻ cả ( giống như kiểu dữ liệu nguyên thuỷ của máy tính) mà nó được XÂY DỰNG từ sự kết hợp với nhiều các đối tượng khác, tuỳ vào độ phức tạp mà các bạn muốn mô phỏng.

**Comment by Jacobvu84** [comment]
Tại sao tôi muốn nhấn mạnh tới 2 từ XÂY DỰNG. Bởi vì xây dựng là cách mà chúng ta bố trí, đặt để các đối tượng theo một `mối quan hệ` nào đó để tạo ra `cấu trúc` phù hợp với nhu cầu sử dụng.

Để tạo ra cấu trúc phù hợp người ta cần phân tích và THIẾT KẾ ( design) cũng như đưa ra các `nguyên tắc` (principle) trong xây dựng, thiết kế nhằm tránh những rủi ro đã nảy sinh trong quá khứ hoặc sẽ gặp phải trong tương lai. Hoặc để tối ưu vấn đề gì đó. 

Những rủi ro đó có thể là sự xung đột hoặc ảnh hưởng qua lại giữa các thành phần trong tổng thể cái mà mình muốn xây dựng và họ đưa ra tất cả những `nguyên tắc` là để giảm hoặc tránh những ảnh hưởng này.

Trong lập trình cũng có những luật, `nguyên tắc` cơ bản đến cao cấp như SOLID, KISS, DRY, DAMP...... bạn chưa cần tìm hiểu nó vội nhưng cái tôi muốn bạn hiểu là nếu ko tuân theo nó phải sẽ gặp rắc rối trong tương lai hoặc các vấn đề khác khi phạm vi bài toán của bạn mở rộng hơn.

Tôi lấy ví dụ thế này. Khi bạn tập đi xe máy trong sân nhà bạn. Ok thoải mái đê miễn sao không đổ xe là được. Tạt ngang, tạt dọc... Nhưng nếu bạn ra đường lúc này bài toán không phải một mình bạn lái xe nữa mà nhiều người cùng lái xe. Nếu không tuân thủ `luật giao thông` đi ngoài đường cũng như trong vườn thì đích thị bạn là Lead - Ninja. =]] ( đùa thôi. Ai đi Lead đừng giận). Sự di chuyện của bạn khi chung với mọi người sẽ gặp rủi ro. Trong lập trình cũng vậy. Bạn làm một mình. Bạn chẳng cần cấu trúc cứ miễn sao code copy đâu đó chạy được là được. Để code bất cứ chỗ nào bạn thích miễn bạn nhớ. Nhưng thật khốn khổ khi thêm một người nữa. Họ không biết đoạn code xử lý abc có chưa, nếu có rồi thì tìm ở đâu. Vì bạn viết có cấu trúc gì đâu mà tìm. Thậm trí treo đầu dê bán thịt chó. Tên class đặt một kiểu bên trong là một mớ hỗn độn các method có khi chẳng liên quan.

Rồi người thứ 2 đó. Để tiện cho họ và cũng như bạn. Họ tự sắp đặt code theo kiểu của họ. Và khi mà có thêm người thứ 3, thứ 4, thứ ..n vào và ai cũng vậy thì đúng là một mớ hỗn độn với những đoạn code trùng nhau ở khắp nơi. 

Nên trước khi viết code bạn cần học các nguyên tắc, cũng như trước khi ra đường bạn phải học luật và phải tôn trọng nó.

**Comment by Jacobvu84** [comment]
Nhân đây gửi tới các bạn đang học trở thành automation tester với mong muốn tự mình xây dựng một framework. Mong các bạn bỏ ngay ý định đó đi. Thực sự nó chỉ làm tốn thời gian tiền bạc của chính các bạn và công ty. 

Ngay cả người trong ngành IT có nền tảng lập tình tốt cũng khó có thể xây dựng được một cái có thể đáp ứng được công việc. Chứ đừng nói các bạn học IT bỏ nghề qua làm Manual Tester hoặc các bạn Manual Tester ở các ngành khác qua học vài buổi cơ bản Core Java hay Selenium mà có thể `build automation framework from scratch`. 

Lý thuyết thì mọi cái có thể nhưng hãy nhìn vào thực tế.

**Comment by hainguyen168** [comment]
> Nhân đây gửi tới các bạn đang học trở thành automation tester với mong muốn tự mình xây dựng một framework. Mong các bạn bỏ ngay ý định đó đi. Thực sự nó chỉ làm tốn thời gian tiền bạc của chính các bạn và công ty.

Anh có thể chia sẻ thêm về quan điểm này không ạ? Theo em thì việc tự xây dựng một framework from scratch cũng giúp ích nhiều cho việc học code, apply những lý thuyết học được vào thực tiễn.

**Comment by Jacobvu84** [comment]
@hainguyen168 

Nếu em có suy nghĩ này tại sao em không theo con đường của một Developer ? mà lại học code qua công việc của một Automation Tester ?
