### ISSUE TITLE
Bạn nên chuẩn bị điều gì trước khi tham gia tranh luận

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#27]
Những năm gần đây, tôi có những trải nghiệm xấu xí trong các mối quan hệ việc làm, đôi khi là trong cuộc sống. Nhưng trong cuộc sống thì ít thôi. Vì bản tính tôi không thích giao du rộng rãi. Đôi khi trong công việc thì không thể tránh được.

Vấn đề khi có những mâu thuẫn, nó có thể giúp ích cho bạn đó là những mâu thuẫn tích cực và cũng có cái mâu thuẫn tiêu cực.
Phần nhiều là các mâu thuẫn tiêu cực. Bởi trong công việc, phần lớn những người tham gia thảo luận đều hóa thân vào công việc đang làm. Nên đánh giá công việc họ sẽ coi đó là việc đánh giá con người.

Họ có tư duy lấy mình làm trung tâm và hóa thân vào mọi cái bạn nói đến. Bởi thế rất mệt mỏi khi nói chuyện với những kiểu người như vậy.

**Cuộc sống**
Bây giờ ai đó nói với tôi. Hmm mày là con chó ( You are a dog). Lập tức bạn liên tưởng bạn có 4 chân, lông lá đầy mình và phát khùng lên vì trong đầu bạn hình ảnh con chó thật **là thứ hạ đẳng**. Nhưng nếu bạn rất yêu con chó, bạn dẫn nó ra ngoài công viên và gọi nó **là "con", là "cục cưng".** Ai đó đi qua nói với bạn. Trời ơi, giống mẹ quá, xinh quá, đáng yêu quá. Lúc này bạn có giận không ? Nếu so sánh con chó với bạn. Bạn không giận nhưng so sánh bạn với con chó sao bạn lại giận, cho dù kết quả đều là bạn = chó hay chó = bạn. Thâm chí tôi từng đọc, nếu ở phương tây bạn với người đàn ông câu đó họ rất vui. Vì họ nghĩ rằng bạn đang khen họ. Vì chó là biểu tượng cho sức mạnh của tình dục. ( không đảm bảo, là họ có đấm bạn như ở Việt Nam hay không, tôi chỉ đọc vậy)

Qua ví dụ này bạn thấy đó. Chỉ va chạm bạn cần nắm rõ trong đầu họ đang nắm giữ điều gì. Đó là cái khó của cuộc sống vì mỗi người có một suy nghĩ khác nhau. Hoặc họ cho thứ đó là hạ đẳng hoặc họ cho nó là tục tưng. Nên cùng một câu nói có thể bạn gặp họa hoặc gặp phước, tùy vào thế giới quan của người đối diện

**Công việc**
Công việc là một phần của cuộc sống. Nó có những ranh giới, bên trong ranh giới đó nó có những nguyên tắc cụ thể. Mà trước khi lao vào ranh giới đó bạn cần học nó trước khi làm nó. Giống như lập trình nó có những nguyên tắc ( princples) mục đích của nó cũng là để "phân chia ranh giới" giữa các đối tượng trong hệ thống. Để tránh mâu thuẫn hoặc ảnh hưởng khi bất cứ đối tượng nào trong hệ thống gặp vấn đề. Nó được đề cập trong tính chất đóng gói của OOP. Vậy để học lập trình trước tiên bạn phải hiểu về OOP. Hiểu về các tính chất của nó. Đằng sau các tính chất đó nó có những nguyên tắc gì và lợi ích ra sau. Trước khi bạn đặt tay gõ code.

Trong công việc nếu bạn làm mà không có phương pháp luận, không có sứ mệnh, không có tầm nhìn... ( định trước cái cần làm và những thứ sẽ bám vào nó để đạt mục tiêu) bạn sẽ rơi vào việc lan man vì không có cái để bấu víu vào. Bạn sẽ đuối lý khi tranh luận và dẫn tới việc "cuồng ngôn đoạt lý" và để "chiến thắng" bạn xoay từ vấn đề công việc sang công kích con người. Đó là biểu hiện của kẻ ích kỷ, lấy cái tôi đè nén người khác. Sẽ thật là thảm họa nếu chọn ai đó làm việc lâu nắm đưa họ lên quản lý mà không được trang bị phương pháp luận cũng như đào tạo về nó. Sống lâu lên lão làng, là cái mà chúng ta đang thấy. Hay không bằng hên, đôi khi bạn cứ ở lại lâu ở công ty bạn sẽ được cất nhắc, điều này tôi biết một chút khi đọc cuốn "dự án phượng hoàng".

Và khi không có cơ sở lý luận, phương pháp luận trong công việc nó dẫn đến những cuộc cãi va non-stop khi có mâu thuẫn trong công việc. Họ lại lấy các nguyên tắc trong cuộc sống mang vào. Thay vì tập trung giải quyết vấn đề trong công việc. Họ bắt đầu mượn gió, bẻ măng, đánh lái hoặc ngầm ý ám chỉ về con người bạn. 

Biểu hiện đó là của những người **không có học**. Không có học không đồng nghĩa với nhân cách của họ thấp. Vì trong cái học nó gồm LỄ - VĂN, là ĐẠO ĐỨC và TRÌNH ĐỘ. Mà vấn đều đang bàn bạc nó liên quan tới công việc, liên quan tới Trình Độ chứ không liên quan cuộc sống, liên quan nhân cách của bạn. 

Trong DDD có câu. 

> No meaning without context

Mọi cái đều có ý nghĩa riêng cho ranh giới của nó. Trước khi phát ngôn bạn nên tỉnh táo nhìn lại vị trí của mình.

Trong thảo luận đôi khi bạn nghe được các câu kiểu như: 
- Vấn đề đơn giản như vậy mà còn không hiểu thì đủ hiểu bạn là người như thế nào 
- Anh không biết gì thì đừng có comment.

Nếu làm gắt ra, những điều trên hoàn toàn có thể gửi lên bộ phận compliance. Để dạy lại code of conduct nếu có.

Thay vì như vậy hãy đặt những câu hỏi WHY ? WHY? WHY ? WHY ? and WHY ?
- Tại sao anh lại nói như thế ? Nó dựa trên cơ sở nào ?
- Điều gì sẽ khiến vấn đề này tốt hơn và thực hành nào tốt để áp dụng nó

Trước khi bạn va chạm thực tế như làm việc, thảo luận, "cãi nhau", hay có những xung đột  bạn phải thấm nhuẫn **cơ sở lý luận và các phương pháp luận** của nó. Bám vào nó bạn sẽ hiểu sâu hơn về nó. Có thể bạn phát hiện ra nó sai lầm để tìm một phương pháp luận khác hoặc bạn tìm ra được yếu điểm của phương pháp luận đó. 

Như một câu nói trước đây tôi từng đọc: Bạn sẽ dừng không sử dụng framework ABC nào đó khi bạn đã quá hiểu về nó. 

Hiểu kỹ rồi thì tại sao lại bỏ. Vì bạn thấy trong đó không có cái bạn cần tìm. Nhưng để tìm ra được cái giới hạn đó, bạn cần không ngừng tìm hiểu và học về nó. Một trong những cách học là thảo luận cùng mọi người. Nếu bạn tập trung vào việc tìm hiểu về công cụ, bạn sẽ không bị distract bởi những thứ không liên quan.  Trong tình huống này việc tìm hiểu công cụ, hay framework đó có thể coi là kim chỉ nam cho cuộc thảo luận mà bạn tham gia vào.

Bạn có thể phát hiện ra những gì mình đang theo đuổi đã cũ, đã lỗi thời hoặc một cái gì đó hữu ích hơn cho công việc của bạn khi bạn có định hướng cho các cuộc thảo luận.

Nếu bạn tham gia vào cuộc thảo luận mà không có bất cứ thứ gì, Không kìm chỉ nam, không mission, không phương pháp luận... 100% bạn chỉ là kẻ phá bĩnh và ném đá. Vì bạn ko biết mục tiêu mình cần đạt được trong công việc là gì. Nếu bạn có hãy bám vào phương pháp luận đó, công cụ đó, mục tiêu đó. Như vậy bạn mới có cái để mà so sánh với của người khác, xem của họ hay của mình có ưu điểm và  nhược điểm gì, Ưu và nhược điểm đó ảnh hưởng trong bối cảnh nào. Và Bài học.

Nếu bạn ko có gì. Chỉ bám vào kinh nghiệm cá nhân. Nói không có sách, mách không có chứng. Chỉ làm theo thói quen và bắt chiếc người khác.... vin vào đó không chịu tiếp thu thì bạn "chưa lớn" hoặc "không chịu trưởng thành"

Người tìm ra phương pháp luận có thể không phải là người làm giỏi nhất trong lĩnh vực đó nhưng họ có khả năng tìm ra được quy luật ( rule) cho vấn đề mà bạn đang làm. Bạn sẽ không tìm thấy các tỷ phú thế giới đạt giải Nobel về kinh tế. Cho dù họ làm kinh tế rất giỏi, viết sách rất hay toàn là các Best Seller nhưng đó chỉ là các quyển sách kể về trải nghiệm và đời tư của họ. Nó không phải là cái nâng lên thành lý luận được. Tôi tin là bạn không tim thấy Bill Gates, Jack Ma, Jeff Bezos, Mark Zuckerberg....trong danh sách những [người đạt giải nobel về kinh tế](https://vi.wikipedia.org/wiki/Danh_s%C3%A1ch_ng%C6%B0%E1%BB%9Di_%C4%91o%E1%BA%A1t_gi%E1%BA%A3i_Nobel_Kinh_t%E1%BA%BF)

Cái mà bạn cần là đứng trên vai những người đó khi bạn đứng chưa vững mà lo tập đi, tập chạy. Hậu quả.... là ngã sml

**Comment by hahoainhi** [comment]
Cảm ơn anh vì cách đặc vấn đề rất hay và có lồng thêm tính chất nghề nghiệp vào bài viết. Theo em,  chúng ta cần học cách kiểm soát cảm xúc và suy nghĩ để có thể đưa ra những ý kiến khách quan. Điều đó sẽ giúp sớm tìm ra giải pháp cho vấn đề đang quan tâm đồng thời sẽ tránh đưa cuộc tranh luận thành 1 buổi công kích nhau.
