### ISSUE TITLE
Remember two basic rules

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#39]
One of the most common requests I get from testers is "can you help me learn Selenium."

There are thousands of tutorials and courses that promise to teach you Selenium in a few days or weeks.

They are lying.

The truth is, if you START by learning Selenium, sooner or later things start going sour. You'll struggle to keep up with the pace. Your tests will feel brittle and break constantly. You'll feel helpless to do anything out of your comfort zone without a developer's help.

But it doesn't have to be that hard, though. You just need to remember two basic rules:
👉 Start with the fundamentals: test automation is coding, and the more fluent you are at coding, the easier you will find Selenium, and all the other tools you'll need to use;
👉 Spend time understanding the business problem you are solving, and learn how to articulate them clearly, before you dive into automating test scripts; manual test scripts are generally the WORST place you can start with automation.

Focus on mastering these basics first, THEN look at Selenium. Guaranteed, you'll find it MUCH, MUCH easier.

Are you learning test automation?

I've prepared a short document to help testers come up with a learning strategy that works: leave a comment if you're interested and I'll share the link.

From John Ferguson Smart

**Comment by Vinhbq1997** [comment]
Hi Jacob, you can share this document for me?

**Comment by Jacobvu84** [comment]
Hey man. Should follow this man on Linkedin https://www.linkedin.com/in/john-ferguson-smart/

**Comment by Vinhbq1997** [comment]
Thanks a lot, have a nice day!
