### ISSUE TITLE
Phân tích mặt hạn chế của mô hình Page Object

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#5]
Đây có thể nói [Page Object](https://martinfowler.com/bliki/PageObject.html) là mô hình phổ biến nhất hiện này. Ý tưởng về thiết kế này được thiết kế bởi [Simon Steward](https://www.linkedin.com/in/sistewart/)

![image](https://user-images.githubusercontent.com/983936/111435720-b41fd900-8733-11eb-9cab-262cb3f2745c.png)

Xem xét về mặt ý tưởng thì nó giải quyết bớt được gánh nặng cho "cái cột điện" ( Base Class) như đề cập ở bài https://github.com/Jacobvu84/diary-testing/issues/4. Lúc này có vẻ như sự cồng kềnh, phức tạp đã được giảm bớt. Thay vì tập trung hết ở một Base Class thì nó được chia theo Page Class. 

Các action ( step) hoặc nghiệp vụ chia theo trang được lưu trữ theo từng trang. Giống như là dây điện của thằng nào thì thằng đó tự dựng cột điện riêng. Không có chung đụng gì cả.

Nhưng thực sự vấn đề này đã được giải quyết một cách triệt để ?

Câu trả lời là không ? 

Pages Objects thực sự dễ bảo trì hơn nhiều so với các script viết theo kiểu keyword.
Keyword hoạt động tốt cho **các tình huống đơn giản**. 

Nhưng nếu như một trang có cấu trúc UI "phức tạp" hoặc có quá nhiều sự thay đổi hoặc các nghiệp vụ tiếp theo có thể thêm vào, dần dần nó cũng sẽ "béo" lên và kích thước lúc này nó có thể to như Base Class. Lúc này chúng ta lại quay lại với cơn ác mộng bảo trì ( maintain code)

Một trong những nguyên nhân phức tạp về mặt UI mà các bạn có thể thấy là do công nghệ js phát triển nó có thể tạo ra các rich UI element. Nghĩa là các element có thể thực hiện được nhiều thao tác thay vì theo truyền thống enter vào filed, click vào button, select....

Có thể bạn chưa hình dung ra chữ phức tạp, tôi sẽ chỉ cho bạn thấy. Lấy một ví dụ những rich UI element dưới đây
![image](https://user-images.githubusercontent.com/983936/111022769-78b99d80-8407-11eb-9d70-1e556b8adf71.png)

Tôi tin là các bạn đã ít nhiều đã đối mặt với sự phức tạp này như TimePicker, hay như JavaScript/HTML5 ComboBox ( nhìn nó giống thẻ select html đó nhưng nó ko phải vậy)

Và các bạn thử nghĩ xem các đối tượng này xuất hiện ở các trang. Các bạn phải viết nhiều mã hơn ở các trang. Để có thể tái sử dụng ( re-use ) code có thể bạn sẽ lại tạo ra một cái Base Class để cho các Page extends và chúng ta đang quay lại cái vấn đề của Keyword.

Đặc tính của công nghệ là sự thay đổi. Công nghệ ngày nay họ tạo ra trang web không còn đơn giản như ngày xưa. Khi bạn cố gắp dùng ý tưởng của Page Object để mô hình bài toán kinh doanh ( business rule) sản phẩm theo trang. Bạn sẽ gặp phải các class lớn và phức tạp Mà đã lớn và phức tạp thì nó lại liên quan tới KHÓ MAINTAIN.

**Comment by Jacobvu84** [comment]
Nếu bạn nào từng trải qua với mô hình này trong các dự án có quy mô thì sẽ nhận ra một điều **thời gian và công sức** để tạo ra hàng chục, hàng trăm page class là một vấn đề nan giải. Nó tốn kém.

**Comment by Jacobvu84** [comment]
Một giới hạn nữa là KHÓ ĐỌC - KHÓ HIỂU

Thông thường là phần page class mọi người sẽ viết lẫn lộn ( mix) cả phần tìm kiếm (locate) element  và tương tác ( interact) với element trong cùng một class này. Điều này sẽ làm cho mã code ở class nhiều lên, mà nhiều lên lại dính tới vấn đề bảo trì và như phân tích ở bài https://github.com/Jacobvu84/diary-testing/issues/4 khi bạn cần chỉnh sửa một một cái gì đó nó có thể gây ảnh hưởng tới test case khác.

Chưa thấy khó đọc và khó hiểu chỗ nào cả ?
À. Như tên gọi của nó Page Object khi tiến hành triển khai code theo mô hình này bạn có xu hướng tâm trung xử lý các logic của bạn toán trên phạm vi mỗi trang. 

Giả sử bài toán kinh doanh của bạn ( business logic) nó cần phải đi qua vài trang mới đủ để người ta hiểu rõ đó là nghiệp vụ gì. Thì việc mô tả theo trang sẽ làm cho bài toán đôi khi trở nên rời rạc, không liên mạch. Giống như bạn viết một câu mà không có chấm, phẩy rõ ràng. Các mô tả bài toán bị bẻ nhỏ theo trang

Lấy ví dụ vui thế này. "Mỗi gia đình có 2 con vợ chồng hạnh phúc"

Phần trên page 1 sẽ là: "Mỗi gia đình có 2 con vợ"
Phần trên page 2 sẽ là: "chồng hạnh phúc"

Khi đọc code kiểu này thì làm sao mà hiểu được cuối cùng thì kịch bản của bạn đang kiểm tra cái vấn đề gì ?

Đấy là tôi ví dụ vui để các bạn hiểu rằng: các phần mô tả bài toán cần test nó nằm ở nhiều trang khác nhau.

Trên thực tế thì các bạn ít khi viết hoặc mô tả các tương tác trên page mà dùng các câu mô tả theo câu chuyện như vậy lắm. Các bạn chỉ tập trung vào việc mô tả bài toán kinh doanh của công ty bằng việc thể hiện sự tương tác dựa trên UI. Mà tập trung mô tả nghiệp vụ dựa trên UI thì làm sao có thể hiểu được nghiệp vụ bên dưới của domain.

**Comment by HoangHien120398** [comment]
@Jacobvu84 Anh ơi em có đọc bài chia sẻ của anh, em có vỡ ra được nhiều điều, em có một thắc mắc là với vấn đề anh nói chỗ page class mọi người thường hay mix cả locate và interact.
Vậy mình có thể chia ra thành 2 package interface và action 
Trong mỗi package trên sẽ có abstact/common và các page class cần có 
thì anh nghĩ như vậy có được không ạ. Em là newbie nên chưa hiểu rõ lắm cũng chưa làm các dự án lớn để có thể hiểu hết được các issuse trong các mô hình nên mong anh có thể trả lời câu hỏi của em ạ. 
Em cảm ơn anh ạ.

**Comment by Jacobvu84** [comment]
@HoangHien120398 Well well. Đó là những ý tưởng tuyệt vời. Em nên làm như vậy.
