### ISSUE TITLE
TEST CASES được thiết kế bởi Manual Tester có phù hợp cho việc tự động hóa

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/diary#9]
Hãy phân tích một chút về Manual Test Cases

###  Số Lượng Nhiều
Phải nói là nhiều về mặt số lượng. Cá nhân tôi nghĩ cái gì nhiều chưa chắc đã tốt vì cái gì nhiều thì thường là dễ dàng tạo ra. Trên thực tế cái gì dễ tạo ra thường mang lại giá trị không cao.

Khi có quá nhiều thứ same same như nhau rất khó để đánh giá xem cái nào quan trọng hơn cái nào. Có lẽ là phải đánh mức độ ưu tiên Test Case theo nhóm. Thay vì trước đây có 1 2 test cases có mức độ ưu tiên cao vì tính quan trọng của nó thì giờ đây có 10, 20. Như vậy về bản chất bên trong **ý nghĩa** của chữ `quan trọng` đã bị hạ xuống. Giống ngày xưa cả lớp có 1 em học sinh giỏi. Giờ học sinh giỏi đã trở nên đại trà. Thì từ GIỎI không còn ý nghĩa trong việc phân loại nữa trong phạm vi cái lớp đó nữa.

Lý do tại sao họ thích nhiều test cases à. Tôi nghĩ ra một lý do mà tôi từng chứng kiến là để thể hiện cho một "con số đầy màu mè" trên báo cáo tới lãnh đạo rằng: Mức độ bao phủ sẽ tỷ lệ thuận với số lượng test cases. Nhiều thế này thì các ngài cứ yên tâm là chúng tôi đã "bao phủ" hết rồi và chúng tôi đang rất là CHĂM CHỈ đấy. Lúc này tôi nghĩ tới quyển sách "Đừng Làm Việc Chăm Chỉ Hãy Làm Việc Thông Minh" mà bạn tôi vừa mua để đọc cho tôi nghe mỗi khi đi cafe.

###  Rườm rà
Không nên dùng từ phản cảm. 
Nói một cách tích cực là Test Cases được viết rất chi tiết, rất chi tiết, QUÁ chi tiết. 

Lý do của việc `chi tiết` này chủ yếu là do tester tập trung vào việc mô tả test case theo dạng viết ra các chỉ dẫn sử dụng (instructions), HOW - Làm sao để tương tác với hệ thống hơn là mô tả nghiệp vụ (WHAT and WHY) của hệ thống, khiến cho người mới tham gia dự án dưới vai trò newbie khó có cái nhìn tổng quan về yêu cầu và mục đích của sản phẩm. 

Sự **rườm rà** dường như là cái để phục vụ cho cái **Nhiều** đã nói ở trên vì chỉ có cách này mới tạo ra được nhiều case. 
Thực tế tôi từng chứng kiến có gần 90 test cases cho một cái màn hình login.

Bên cạnh đó việc áp dụng các kỹ thuật được hướng dẫn trong các chứng chỉ như phân vùng, bảng quyết định, khiến cho số lượng các case kiểm tra validation tăng phi mã theo giai thừa chứ ko phải cấp số nhân. Bạn thử tưởng tượng xem, một form/page mà có khoảng 10 elements thôi. Họ vẽ cái bảng decision table rồi tổ hợp các tình huống valid và invalid thôi cũng thấy số lượng test case nó khủng như nào rồi. Đó mà có lỗi gì được. Mà một sản phẩm đâu phải có vài page. Số Test Case lên cả ngàn....

###  Trùng lặp

Bởi sự chi tiết quá độ nên khi đọc test case phần lớn là sự trùng lặp. 

Một bài viết mà tôi tâm đắc nói về `con đường hạnh phúc`, bạn có thể tham khảo [ở đây](https://www.linkedin.com/pulse/e2e-mountain-andreas-worm/) để giảm bớt sự trùng lặp đó là hãy tập trung vào con đường hạnh phúc có tên E2E. Đến nơi bạn muốn đến đừng có mải đuổi hoa bắt bướm.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/983936/111290350-a8231100-8678-11eb-80ec-9d2ec8ba494f.png">

Giả sử một test case nào đó của bạn cần đi qua 6 pages khác nhau mới đến trang bạn cần test thì có rất nhiều cases sẽ trùng lặp các steps từ trang 1 đến trang 3 hoặc trang 4, trang 5 rồi từ các trang trung gian này bắt đầu rẽ nhánh đổ vào các con sông, con kênh nhỏ ( tương ứng với các test case nhỏ). Điều này làm tôi liên tưởng đến cái rễ cây. Có 2 loại rễ là rễ chùm và rễ cọc. Mấy cây mà có rễ chùm đảm bảo cũng một cơn gió nó sẽ bật gốc trước. 

Nó chính là hình ảnh minh họa cho mức độ flaky test. Nếu bạn chưa từng nghe khái niệm này có thể tham khảo nó [ở đây](https://engineering.atspotify.com/2019/11/18/test-flakiness-methods-for-identifying-and-dealing-with-flaky-tests/)

Bây giờ, tôi sẽ kể một vấn đề thực tiễn. Để tôi hỏi bạn một câu hỏi.

Bạn có đảm bảo rằng test cases mà bạn đang dùng để thực hiện việc thử nghiệm luôn là được update mới nhất.

Tôi cá là 100% không.

Phần lớn các "senior tester" sau một thời gian dài tham gia dự án, họ gần như nắm rõ sản phẩm như lòng bàn tay. Test là khỏi cần xem hay đọc test cases. Nên ko có chuyện họ dành thời gian để update những thay đổi này trong các file excel hay hệ thống quản lý test cases.

Khi sản phẩm có sự thay đổi ( thay đổi về code, về mở rộng nghiệp vụ hoặc đơn giản dev cảm thấy giải pháp mới của họ tốt hơn giải pháp cũ) các test cases sẽ không còn đúng theo từng step nữa. Họ sẽ ko thực hiện việc update các test case vì chúng nhiều và phân tán ở nhiều chỗ trong các sheets và các file excel khác nhau

Trừ khi là bạn vừa test vừa đọc và rà soát lại. Cái này thực sự là phù hợp cho tester mới vào. Vừa Test vừa hỏi các senior vì sao có sự khác biệt này và sau đó là update. Nhưng như vậy chỉ khi nào có nhân sự mới thì công việc đó mới được làm.

Điều này thật tồi tệ nếu test case được quản lý trên công cụ quản lý chuyên nghiệp như là testLink, TestRail, TestFlo...... tha hồ mà tìm, rồi edit. Nó còn mất thời gian hơn ở trên file excel rất nhiều

Và đến đây bạn đã thấy chúng ta sẽ thu được kết quả như thế nào nếu automated những test case này chưa?

Ngay cả việc sửa bằng tay còn vất vả. Huống hồ là các kịch bản auto cũng được viết steps by steps như manual test case. Muôn đời chỉ có chạy theo auto. Làm nô lệ cho auto chứ không phải dùng auto phục vụ cho team.

Từ ý định dùng auto test để thay thế và giúp giảm thiểu công sức cho con người thì giờ đây ta nằm ngủ với cơn ác mộng **MAINTAIN**. 

`Dẫn tới thời gian để làm test không có, suốt ngày lo update và maintain kịch bản auto. Sản phẩm bị bỏ bê dẫn tới kém chất lượng và kết quả là lãnh đạo đánh giá. Auto chỉ là thứ lý thuyết vớ vẩn`. Và tôi đoán chắc họ sẽ dẹp nó nhanh vì mục đích của họ không đạt được. 

Đến đây tôi hi vọng và mong rằng những người hoạt định chiến lược có thêm thông tin tham khảo để quyết định xem chúng ta có nên dùng automation test cho mục đích thay thế một phần công việc của Manual QA hay không ? 

Nếu có thì ta Test Case như thế nào mới phù hợp cho làm auto Test.

**Comment by Orcdl** [comment]
@Jacobvu84 : cám ơn chia sẻ ngắn gọn và rất rõ ràng của tôi. Tôi xin chia sẻ thêm vài ý kiến nhỏ với kinh nghiệm của bản thân mình. Bản thân mình đang làm việc với role là Manual QA nha. Team hiện tại của mình là 1 QA - 4 devs - development 1 product. Tốc độ release trung bình là 1 tuần/ release. Mỗi lần release sẽ có khoảng 4-5 features  mới.

**Testcase số lượng nhiều + rườm rà:**
- Việc này mình hoàn toàn đồng ý với bạn, việc ngồi tỉ mẩn viết từng bộ testcase sẽ là rất mất thời gian và thường xuyên bị out-update. 
**Nhưng** điểm hay của có testcase này là: 
- giúp cho mình tracking lại những case mình đã thực sự test qua rồi, đặc biệt khi mà khối lượng công việc nhiều và bạn phải switch qua lại giữa các feature là việc bình thường, trí nhớ con người lại hữu hạn. 
- Góp phần giảm thiểu thời gian test cho regression testing

Để giảm thiểu bớt sự rườm rà của testcase, cách giải quyết hiện tại của tôi là: vẽ userflow đối với một feature, tạo checklist cho exit criteria và 1 checklist cho tất các các happy case, worse case mà không có phần expectation. Mặc dù bản thân tôi thấy cách này vẫn chưa thực sự tối ưu nhưng nó phù hợp với scope of work của team tôi hiện tại. 
Và tất nhiên, tôi vẫn đau đáu về một testcase **phù hợp cho auto test:**
- Có  dùng được cho cả Auto tester,  Manual tester  và Dev (dev có thể dựa vào testcase để viết unit test)
- Có thể dễ dàng maintain 
- Có thể dễ dàng update

Xin hãy chia sẻ giúp tôi solution mà bạn hiện có hoặc phương pháp nào mà bạn đã từng ứng dụng (well, it's work). Cám ơn bạn!

**Comment by Jacobvu84** [comment]
@Orcdl well, Cám ơn chia sẻ của bạn. Nó rất quý báu và giúp chúng ta có thể tìm kiếm thêm gì đó để công việc tốt hơn.

Bạn thừa nhận Test Case bị out of date. Điều này đồng nghĩa với việc đó là những test case đã chết.

Nếu bạn dùng cái xác của nó để xem tracking và lưu nhớ là điều tốt nhưng hãy để việc đó cho một công cụ quản lý test. Nó giúp bạn kiểm tra nhanh hơn trong nghĩa trang đó có bao nhiêu cái xác. Nên việc viết chi tiết là ko cần thiết.

Bạn thấy đấy ngày nay ko khó để nhìn thấy đứa trẻ rất bé chơi game trên máy tính bảng hoặc điện thoại. Nêú sản phẩm của bạn khó dùng tới mức cần phải có một tài liệu step by step như vậy. Cá nhân mình cho rằng nên xem lại UI/UX.

Một điều nữa với test case chi tiết nó làm người sau ko còn khả năng test theo phán đoán của họ nữa. Nó trở thành con đường mòn cho bất cứ người nào dùng đến nó. 

Chốt lại: Vứt bỏ sự rườm rà.

Về vấn đề này bạn có thể tham khảo blog này 
- https://testing.googleblog.com/2011/09/10-minute-test-plan.html?m=1

**Comment by Jacobvu84** [comment]
Cách giải quyết của bạn theo tôi là hợp lý khi tạo ra một checklist như bạn nói. Trong bài viết tôi cùng có đề cập nó trong link 2e2 mountain.

Về vấn đề kiểm tra hồi quy tôi có vài câu hỏi:
Lý do gì bạn nghĩ rằng cần test hồi quy ?

**Comment by Jacobvu84** [comment]
Về vấn đề Test case nào phù hợp cho auto ?
Chúng ta cần làm rõ vài điều
- Có bao nhiêu loại hình test: Nếu là Unit Test đó là công việc Dev. Tôi nghĩ ko có manual Test case nào phù hợp cho nó cả. 

Về mục tiêu của unit Test: Bạn đọc ở đây 
- https://livebook.manning.com/book/unit-testing/chapter-1/1

Bằng cái nào đó bạn cũng sẽ tìm đc đáp án trong câu hỏi của tôi về vấn đề test hồi quy

**Comment by Jacobvu84** [comment]
Về vấn đề test case dễ maintain hay dễ mở rộng. Tôi cho rằng bạn đang nói đến vấn đề viết code cho auto test.

Nếu đúng thì đây là vấn đề của người viết code, họ có đủ kỹ thuật, trình độ cũng như vận dụng thành thào các nguyên tắc trong lập trình hay ko.

Về vấn đề này tôi hoàn toàn có thể giải quyết với các công cụ đc thiết kế bởi Technical Architect thay vì các Automation Tester. 

Hoan nghênh. Tôi rất muốn trao đổi hơn nữa về suy nghĩ test hồi quy của bạn
